interface types {
    variant data-type {
        int32(s32),
        int64(s64),
        uint32(u32),
        uint64(u64),
        float(float64),
        double(float64),
        str(string),
        boolean(bool),
        date(string),
        time(string),
        timestamp(string),
        binary(list<u8>),
        null
    }

    record row {
        field-name: string,
        value: data-type,
    }

    resource statement {
        prepare: static func(query: string, params: list<string>) -> result<statement, error>;
    }

    resource error {
		trace: func() -> string;
  	}

    resource connection {
        open: static func(name: string) -> result<connection, error>;
    }
}
